apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ranch-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CleanSlice/ranch.git
    targetRevision: main
    path: k8s/infrastructure/database
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
