apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranch-admin
  namespace: platform
  labels:
    app: ranch-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranch-admin
  template:
    metadata:
      labels:
        app: ranch-admin
    spec:
      nodeSelector:
        node-role: system
      containers:
        - name: admin
          image: ghcr.io/CleanSlice/ranch-admin:latest
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
