apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ranch-db
  namespace: platform
spec:
  instances: 1
  storage:
    size: 10Gi
  postgresql:
    parameters:
      max_connections: "200"
