// This file is auto-generated by @hey-api/openapi-ts

export const CreateOwnerDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'owner@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UpsertSettingDtoSchema = {
    type: 'object',
    properties: {
        valueType: {
            type: 'string',
            enum: ['string', 'json'],
            default: 'string'
        },
        value: {
            type: 'object',
            description: 'String for valueType=string; any JSON for valueType=json'
        }
    },
    required: ['valueType', 'value']
} as const;

export const CreateLlmCredentialDtoSchema = {
    type: 'object',
    properties: {
        provider: {
            type: 'string',
            example: 'anthropic'
        },
        model: {
            type: 'string',
            example: 'claude-sonnet-4-6'
        },
        apiKey: {
            type: 'string'
        },
        fallbackModel: {
            type: 'string',
            example: 'claude-haiku-4-5'
        },
        label: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['active', 'disabled']
        }
    },
    required: ['provider', 'model', 'apiKey']
} as const;

export const UpdateLlmCredentialDtoSchema = {
    type: 'object',
    properties: {
        provider: {
            type: 'string',
            example: 'anthropic'
        },
        model: {
            type: 'string',
            example: 'claude-sonnet-4-6'
        },
        apiKey: {
            type: 'string'
        },
        fallbackModel: {
            type: 'string',
            example: 'claude-haiku-4-5'
        },
        label: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['active', 'disabled']
        }
    }
} as const;

export const CreateTemplateDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        image: {
            type: 'string',
            example: 'ghcr.io/org/agent:latest'
        },
        defaultConfig: {
            type: 'object'
        },
        defaultResources: {
            type: 'object'
        },
        defaultKnowledgeIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['name', 'description', 'image']
} as const;

export const UpdateTemplateDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        image: {
            type: 'string',
            example: 'ghcr.io/org/agent:latest'
        },
        defaultConfig: {
            type: 'object'
        },
        defaultResources: {
            type: 'object'
        },
        defaultKnowledgeIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const AgentResourcesDtoSchema = {
    type: 'object',
    properties: {
        cpu: {
            type: 'string',
            example: '500m'
        },
        memory: {
            type: 'string',
            example: '512Mi'
        }
    },
    required: ['cpu', 'memory']
} as const;

export const CreateAgentDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        llmCredentialId: {
            type: 'string'
        },
        config: {
            type: 'object'
        },
        resources: {
            '$ref': '#/components/schemas/AgentResourcesDto'
        }
    },
    required: ['name', 'templateId']
} as const;

export const UpdateAgentDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        llmCredentialId: {
            type: 'string'
        },
        config: {
            type: 'object'
        },
        resources: {
            '$ref': '#/components/schemas/AgentResourcesDto'
        }
    }
} as const;

export const SaveFileDtoSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'string',
            description: 'Full file content as text'
        }
    },
    required: ['content']
} as const;

export const CreateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        },
        role: {
            type: 'string',
            enum: ['owner', 'admin', 'member']
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UpdateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        },
        role: {
            type: 'string',
            enum: ['owner', 'admin', 'member']
        },
        status: {
            type: 'string',
            enum: ['active', 'invited', 'disabled']
        }
    }
} as const;

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['email', 'password']
} as const;

export const BridleTextPartDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['text', 'image', 'file'],
            example: 'text'
        },
        text: {
            type: 'string'
        }
    },
    required: ['type', 'text']
} as const;

export const BridleImagePartDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['text', 'image', 'file'],
            example: 'image'
        },
        base64: {
            type: 'string',
            description: 'Base64-encoded image data'
        },
        mediaType: {
            type: 'string',
            description: 'MIME type',
            example: 'image/jpeg'
        }
    },
    required: ['type', 'base64', 'mediaType']
} as const;

export const SendMessageDtoSchema = {
    type: 'object',
    properties: {
        text: {
            type: 'string',
            description: 'Message text (plain-text shorthand)'
        },
        parts: {
            description: 'Rich content parts. If omitted, built from text + images.',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BridleTextPartDto'
            }
        },
        images: {
            description: 'Attached images (legacy — prefer parts)',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BridleImagePartDto'
            }
        }
    },
    required: ['text']
} as const;

export const BridleHealthDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        agentConnected: {
            type: 'boolean',
            description: 'Whether any agent runtime is connected via WebSocket'
        },
        browserClients: {
            type: 'number',
            description: 'Number of browser clients connected'
        }
    },
    required: ['ok', 'agentConnected', 'browserClients']
} as const;

export const BridleBotHealthDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        agentConnected: {
            type: 'boolean',
            description: 'Whether this bot agent is connected via WebSocket'
        },
        browserClients: {
            type: 'number',
            description: 'Number of browser clients connected to this bot'
        },
        botId: {
            type: 'string',
            description: 'Bot identifier'
        }
    },
    required: ['ok', 'agentConnected', 'browserClients', 'botId']
} as const;

export const ReportUsageDtoSchema = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            example: '2026-04-22'
        },
        byModel: {
            type: 'object',
            description: 'Per-model usage. Key is the canonical model name (e.g. claude-sonnet-4-6).',
            example: {
                'claude-sonnet-4-6': {
                    inputTokens: 12345,
                    outputTokens: 6789,
                    callCount: 42
                }
            }
        }
    },
    required: ['date', 'byModel']
} as const;

export const GraphNodeDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        label: {
            type: 'string'
        },
        entityType: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: ['id', 'label', 'entityType', 'description']
} as const;

export const GraphEdgeDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        target: {
            type: 'string'
        },
        weight: {
            type: 'number'
        },
        keywords: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: ['id', 'source', 'target', 'weight', 'keywords', 'description']
} as const;

export const GraphDtoSchema = {
    type: 'object',
    properties: {
        nodes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GraphNodeDto'
            }
        },
        edges: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GraphEdgeDto'
            }
        },
        isTruncated: {
            type: 'boolean'
        }
    },
    required: ['nodes', 'edges', 'isTruncated']
} as const;

export const CreateKnowledgeDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        entityTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        relationshipTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['name']
} as const;

export const UpdateKnowledgeDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        entityTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        relationshipTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const QueryKnowledgeDtoSchema = {
    type: 'object',
    properties: {
        query: {
            type: 'string'
        },
        mode: {
            type: 'string',
            enum: ['hybrid', 'local', 'global', 'naive'],
            default: 'hybrid'
        },
        topK: {
            type: 'number',
            default: 25
        }
    },
    required: ['query']
} as const;

export const KnowledgeQueryReferenceDtoSchema = {
    type: 'object',
    properties: {
        referenceId: {
            type: 'string'
        },
        filePath: {
            type: 'string'
        }
    },
    required: ['referenceId', 'filePath']
} as const;

export const KnowledgeQueryResultDtoSchema = {
    type: 'object',
    properties: {
        answer: {
            type: 'string'
        },
        references: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/KnowledgeQueryReferenceDto'
            }
        }
    },
    required: ['answer', 'references']
} as const;

export const CreateSourceDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['file', 'url', 'text']
        },
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        },
        content: {
            type: 'string'
        }
    },
    required: ['type', 'name']
} as const;

export const ImportSkillUrlDtoSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string',
            description: 'GitHub URL — folder (tree/<sha>/<path>) or file (blob/<sha>/<path>). The folder must contain a SKILL.md or README.md.',
            example: 'https://github.com/supabase/agent-skills/tree/main/skills/supabase-postgres-best-practices'
        },
        name: {
            type: 'string'
        }
    },
    required: ['url']
} as const;

export const ImportSkillDtoSchema = {
    type: 'object',
    properties: {
        repo: {
            type: 'string',
            example: 'anthropics/skills',
            description: 'GitHub owner/repo as returned by /skills/search'
        },
        path: {
            type: 'string',
            example: 'pdf-skill/SKILL.md',
            description: 'Path to the SKILL.md file inside the repo'
        },
        name: {
            type: 'string',
            description: 'Override the auto-derived slug. Lowercase letters, digits and dashes.'
        }
    },
    required: ['repo', 'path']
} as const;

export const CreateSkillDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'devops',
            description: 'Unique slug — lowercase letters, digits, dashes'
        },
        title: {
            type: 'string',
            example: 'DevOps engineer'
        },
        body: {
            type: 'string',
            description: 'Markdown body of the skill'
        },
        description: {
            type: 'string'
        }
    },
    required: ['name', 'title', 'body']
} as const;

export const UpdateSkillDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'devops',
            description: 'Unique slug — lowercase letters, digits, dashes'
        },
        title: {
            type: 'string',
            example: 'DevOps engineer'
        },
        body: {
            type: 'string',
            description: 'Markdown body of the skill'
        },
        description: {
            type: 'string'
        }
    }
} as const;