// This file is auto-generated by @hey-api/openapi-ts

export const CreateOwnerDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'owner@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UpsertSettingDtoSchema = {
    type: 'object',
    properties: {
        valueType: {
            type: 'string',
            enum: ['string', 'json'],
            default: 'string'
        },
        value: {
            type: 'object',
            description: 'String for valueType=string; any JSON for valueType=json'
        }
    },
    required: ['valueType', 'value']
} as const;

export const CreateLlmCredentialDtoSchema = {
    type: 'object',
    properties: {
        provider: {
            type: 'string',
            example: 'anthropic'
        },
        model: {
            type: 'string',
            example: 'claude-sonnet-4-6'
        },
        apiKey: {
            type: 'string'
        },
        fallbackModel: {
            type: 'string',
            example: 'claude-haiku-4-5'
        },
        label: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['active', 'disabled']
        },
        supportsChat: {
            type: 'boolean',
            default: true
        },
        supportsEmbedding: {
            type: 'boolean',
            default: false
        }
    },
    required: ['provider', 'model', 'apiKey']
} as const;

export const UpdateLlmCredentialDtoSchema = {
    type: 'object',
    properties: {
        provider: {
            type: 'string',
            example: 'anthropic'
        },
        model: {
            type: 'string',
            example: 'claude-sonnet-4-6'
        },
        apiKey: {
            type: 'string'
        },
        fallbackModel: {
            type: 'string',
            example: 'claude-haiku-4-5'
        },
        label: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['active', 'disabled']
        },
        supportsChat: {
            type: 'boolean',
            default: true
        },
        supportsEmbedding: {
            type: 'boolean',
            default: false
        }
    }
} as const;

export const LlmHealthCheckResultDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        latencyMs: {
            type: 'number',
            example: 482
        },
        provider: {
            type: 'string',
            example: 'anthropic'
        },
        model: {
            type: 'string',
            example: 'claude-sonnet-4-6'
        },
        error: {
            type: 'string',
            example: 'Anthropic 401: invalid x-api-key'
        }
    },
    required: ['ok', 'latencyMs', 'provider', 'model']
} as const;

export const CreateTemplateDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        image: {
            type: 'string',
            example: 'ghcr.io/org/agent:latest'
        },
        defaultConfig: {
            type: 'object'
        },
        defaultResources: {
            type: 'object'
        },
        paddockConfig: {
            type: 'object'
        },
        defaultKnowledgeIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['name', 'description', 'image']
} as const;

export const UpdateTemplateDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        image: {
            type: 'string',
            example: 'ghcr.io/org/agent:latest'
        },
        defaultConfig: {
            type: 'object'
        },
        defaultResources: {
            type: 'object'
        },
        paddockConfig: {
            type: 'object'
        },
        defaultKnowledgeIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const SetTemplateSkillsDtoSchema = {
    type: 'object',
    properties: {
        skillIds: {
            description: 'Full list of skill IDs to attach. Replaces any prior set.',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['skillIds']
} as const;

export const SetTemplateMcpsDtoSchema = {
    type: 'object',
    properties: {
        mcpServerIds: {
            description: 'Full list of MCP server IDs to attach. Replaces any prior set.',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['mcpServerIds']
} as const;

export const CreateMcpServerDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'object'
        },
        url: {
            type: 'string'
        },
        transport: {
            type: 'string',
            enum: ['streamableHttp', 'sse']
        },
        authType: {
            type: 'string',
            enum: ['none', 'bearer', 'header']
        },
        authValue: {
            type: 'object'
        },
        enabled: {
            type: 'boolean'
        }
    },
    required: ['name', 'url']
} as const;

export const UpdateMcpServerDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'object'
        },
        url: {
            type: 'string'
        },
        transport: {
            type: 'string',
            enum: ['streamableHttp', 'sse']
        },
        authType: {
            type: 'string',
            enum: ['none', 'bearer', 'header']
        },
        authValue: {
            type: 'object'
        },
        enabled: {
            type: 'boolean'
        }
    }
} as const;

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['email', 'password']
} as const;

export const RegisterDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UserRoleTypesSchema = {
    type: 'string',
    enum: ['Owner', 'Admin', 'User', 'Agent'],
    description: 'Server filters Owner/Admin out regardless of what is passed; embed keys cannot grant platform-admin to a visitor.'
} as const;

export const EmbedTokenDtoSchema = {
    type: 'object',
    properties: {
        sub: {
            type: 'string',
            description: 'Subject — used as clientId for routing inside the bridle hub.',
            example: 'user-123'
        },
        email: {
            type: 'string',
            example: 'alice@example.com'
        },
        roles: {
            type: 'array',
            description: 'Server filters Owner/Admin out regardless of what is passed; embed keys cannot grant platform-admin to a visitor.',
            items: {
                '$ref': '#/components/schemas/UserRoleTypes'
            }
        },
        expiresIn: {
            type: 'string',
            description: 'Duration string (s/m/h/d). Defaults to 15m.',
            example: '15m'
        }
    },
    required: ['sub']
} as const;

export const ApiKeyScopeTypesSchema = {
    type: 'string',
    enum: ['embed:mint', 'admin']
} as const;

export const CreateApiKeyDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Marketing site embed'
        },
        scopes: {
            type: 'array',
            example: ['embed:mint'],
            items: {
                '$ref': '#/components/schemas/ApiKeyScopeTypes'
            }
        },
        expiresAt: {
            type: 'string',
            description: 'ISO date string. Omit for a non-expiring key.',
            example: '2027-01-01T00:00:00.000Z'
        }
    },
    required: ['name', 'scopes']
} as const;

export const GraphNodeDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        label: {
            type: 'string'
        },
        entityType: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: ['id', 'label', 'entityType', 'description']
} as const;

export const GraphEdgeDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        target: {
            type: 'string'
        },
        weight: {
            type: 'number'
        },
        keywords: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: ['id', 'source', 'target', 'weight', 'keywords', 'description']
} as const;

export const GraphDtoSchema = {
    type: 'object',
    properties: {
        nodes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GraphNodeDto'
            }
        },
        edges: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GraphEdgeDto'
            }
        },
        isTruncated: {
            type: 'boolean'
        }
    },
    required: ['nodes', 'edges', 'isTruncated']
} as const;

export const CreateKnowledgeDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        entityTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        relationshipTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['name']
} as const;

export const UpdateKnowledgeDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        entityTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        relationshipTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const QueryKnowledgeDtoSchema = {
    type: 'object',
    properties: {
        query: {
            type: 'string'
        },
        mode: {
            type: 'string',
            enum: ['hybrid', 'local', 'global', 'naive'],
            default: 'hybrid'
        },
        topK: {
            type: 'number',
            default: 25
        }
    },
    required: ['query']
} as const;

export const KnowledgeQueryReferenceDtoSchema = {
    type: 'object',
    properties: {
        referenceId: {
            type: 'string'
        },
        filePath: {
            type: 'string'
        }
    },
    required: ['referenceId', 'filePath']
} as const;

export const KnowledgeQueryResultDtoSchema = {
    type: 'object',
    properties: {
        answer: {
            type: 'string'
        },
        references: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/KnowledgeQueryReferenceDto'
            }
        }
    },
    required: ['answer', 'references']
} as const;

export const CreateSourceDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['file', 'url', 'text']
        },
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        },
        content: {
            type: 'string'
        }
    },
    required: ['type', 'name']
} as const;

export const AgentPodStatusDtoSchema = {
    type: 'object',
    properties: {
        agentId: {
            type: 'string',
            example: 'agent-abc-123'
        },
        podName: {
            type: 'string',
            example: 'agent-agent-abc-123'
        },
        phase: {
            type: 'string',
            enum: ['Pending', 'Running', 'Succeeded', 'Failed', 'Unknown'],
            example: 'Running'
        },
        ready: {
            type: 'boolean',
            example: true
        },
        restartCount: {
            type: 'number',
            example: 0
        },
        startedAt: {
            type: 'string',
            nullable: true,
            example: '2026-04-30T10:15:00Z'
        },
        lastTerminationReason: {
            type: 'string',
            nullable: true,
            example: 'OOMKilled'
        },
        containerWaitingReason: {
            type: 'string',
            nullable: true,
            example: 'CrashLoopBackOff'
        },
        message: {
            type: 'string',
            nullable: true
        },
        observedAt: {
            type: 'string',
            example: '2026-04-30T10:30:00Z'
        }
    },
    required: ['agentId', 'podName', 'phase', 'ready', 'restartCount', 'startedAt', 'lastTerminationReason', 'containerWaitingReason', 'message', 'observedAt']
} as const;

export const AgentStatusDtoSchema = {
    type: 'object',
    properties: {
        agent: {
            type: 'object',
            description: 'Agent DB record (id, name, status, etc.)'
        },
        pod: {
            nullable: true,
            description: 'Live pod status; null if no pod is currently running for this agent.',
            allOf: [
                {
                    '$ref': '#/components/schemas/AgentPodStatusDto'
                }
            ]
        }
    },
    required: ['agent', 'pod']
} as const;

export const AgentMcpDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'Unique MCP server name (key in the runtime registry).'
        },
        transport: {
            type: 'string',
            enum: ['streamableHttp', 'sse'],
            description: 'Transport protocol the runtime should use to connect.'
        },
        url: {
            type: 'string',
            description: 'MCP server endpoint URL.'
        },
        authType: {
            type: 'string',
            enum: ['none', 'bearer', 'header'],
            description: 'Auth scheme for the connection.'
        },
        authValue: {
            type: 'string',
            nullable: true,
            description: 'Auth credential. For `bearer`: raw token (runtime adds the `Bearer ` prefix). For `header`: literal `Header-Name: value` line. `null` when authType is `none`.'
        },
        enabled: {
            type: 'boolean',
            description: 'Always `true` in this list — disabled servers are filtered server-side. Kept for forward compatibility.'
        }
    },
    required: ['name', 'transport', 'url', 'authType', 'authValue', 'enabled']
} as const;

export const AgentResourcesDtoSchema = {
    type: 'object',
    properties: {
        cpu: {
            type: 'string',
            example: '500m'
        },
        memory: {
            type: 'string',
            example: '512Mi'
        }
    },
    required: ['cpu', 'memory']
} as const;

export const CreateAgentDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        llmCredentialId: {
            type: 'string'
        },
        config: {
            type: 'object'
        },
        resources: {
            '$ref': '#/components/schemas/AgentResourcesDto'
        },
        isPublic: {
            type: 'boolean',
            description: 'When true, the agent is visible on the public landing page to unauthenticated visitors.'
        },
        allowedOrigins: {
            description: 'Origins (scheme + host + port) authorized to open browser WebSockets to this bot without a JWT. Only consulted when isPublic=true.',
            example: ['https://bridle.cleanslice.org', 'http://localhost:5173'],
            type: 'array',
            items: {
                type: 'string'
            }
        },
        knowledgeIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isAdmin: {
            type: 'boolean',
            description: 'When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.'
        }
    },
    required: ['name', 'templateId']
} as const;

export const UpdateAgentDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        llmCredentialId: {
            type: 'string'
        },
        config: {
            type: 'object'
        },
        resources: {
            '$ref': '#/components/schemas/AgentResourcesDto'
        },
        isPublic: {
            type: 'boolean',
            description: 'When true, the agent is visible on the public landing page to unauthenticated visitors.'
        },
        allowedOrigins: {
            description: 'Origins (scheme + host + port) authorized to open browser WebSockets to this bot without a JWT. Only consulted when isPublic=true.',
            example: ['https://bridle.cleanslice.org', 'http://localhost:5173'],
            type: 'array',
            items: {
                type: 'string'
            }
        },
        knowledgeIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isAdmin: {
            type: 'boolean',
            description: 'When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.'
        }
    }
} as const;

export const SetAgentDebugDtoSchema = {
    type: 'object',
    properties: {
        enabled: {
            type: 'boolean',
            description: 'When true, runtime emits prompt-debug snapshots over the bridle WS to admin clients.'
        }
    },
    required: ['enabled']
} as const;

export const SaveFileDtoSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'string',
            description: 'Full file content as text'
        }
    },
    required: ['content']
} as const;

export const BridleTextPartDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['text', 'image', 'file'],
            example: 'text'
        },
        text: {
            type: 'string'
        }
    },
    required: ['type', 'text']
} as const;

export const BridleImagePartDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['text', 'image', 'file'],
            example: 'image'
        },
        base64: {
            type: 'string',
            description: 'Base64-encoded image data'
        },
        mediaType: {
            type: 'string',
            description: 'MIME type',
            example: 'image/jpeg'
        }
    },
    required: ['type', 'base64', 'mediaType']
} as const;

export const SendMessageDtoSchema = {
    type: 'object',
    properties: {
        text: {
            type: 'string',
            description: 'Message text (plain-text shorthand)'
        },
        parts: {
            description: 'Rich content parts. If omitted, built from text + images.',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BridleTextPartDto'
            }
        },
        images: {
            description: 'Attached images (legacy — prefer parts)',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BridleImagePartDto'
            }
        }
    },
    required: ['text']
} as const;

export const BridleHealthDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        agentConnected: {
            type: 'boolean',
            description: 'Whether any agent runtime is connected via WebSocket'
        },
        browserClients: {
            type: 'number',
            description: 'Number of browser clients connected'
        }
    },
    required: ['ok', 'agentConnected', 'browserClients']
} as const;

export const BridleAgentHealthDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        agentConnected: {
            type: 'boolean',
            description: 'Whether this agent is connected via WebSocket'
        },
        browserClients: {
            type: 'number',
            description: 'Number of browser clients connected to this agent'
        },
        agentId: {
            type: 'string',
            description: 'Bot identifier'
        }
    },
    required: ['ok', 'agentConnected', 'browserClients', 'agentId']
} as const;

export const TranscriptMessageDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'c94dbcf2-64f1-4e84-9723-c94e2d815f61'
        },
        role: {
            type: 'string',
            enum: ['user', 'assistant'],
            example: 'assistant'
        },
        text: {
            type: 'string',
            example: 'Hello, how can I help?'
        },
        ts: {
            type: 'number',
            example: 1777562539964,
            description: 'Unix epoch milliseconds.'
        }
    },
    required: ['id', 'role', 'text', 'ts']
} as const;

export const TranscriptResponseDtoSchema = {
    type: 'object',
    properties: {
        messages: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TranscriptMessageDto'
            }
        },
        channel: {
            type: 'string',
            example: 'admin',
            description: 'Channel the transcript was loaded from.'
        }
    },
    required: ['messages', 'channel']
} as const;

export const SaveTemplateFileDtoSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'string',
            description: 'Full file content as text'
        }
    },
    required: ['content']
} as const;

export const InstallDeclaredSkillDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        resolved: {
            type: 'boolean'
        }
    },
    required: ['id', 'resolved']
} as const;

export const InstallDeclaredMcpDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        resolved: {
            type: 'boolean'
        }
    },
    required: ['id', 'resolved']
} as const;

export const InstallDeclaredSecretDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        required: {
            type: 'boolean'
        }
    },
    required: ['name', 'required']
} as const;

export const InstallDeclaredDtoSchema = {
    type: 'object',
    properties: {
        skills: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/InstallDeclaredSkillDto'
            }
        },
        mcp: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/InstallDeclaredMcpDto'
            }
        },
        secrets: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/InstallDeclaredSecretDto'
            }
        }
    },
    required: ['skills', 'mcp', 'secrets']
} as const;

export const InstallFileCountsDtoSchema = {
    type: 'object',
    properties: {
        agentFiles: {
            type: 'number'
        },
        scenarioFiles: {
            type: 'number'
        }
    },
    required: ['agentFiles', 'scenarioFiles']
} as const;

export const InstallPreviewDtoSchema = {
    type: 'object',
    properties: {
        manifest: {
            type: 'object',
            description: 'The parsed manifest. Returned as raw JSON so the UI can render any field without typed coupling.',
            additionalProperties: true
        },
        willCreate: {
            type: 'boolean'
        },
        willUpgrade: {
            type: 'boolean'
        },
        existingTemplateId: {
            type: 'string'
        },
        declared: {
            '$ref': '#/components/schemas/InstallDeclaredDto'
        },
        files: {
            '$ref': '#/components/schemas/InstallFileCountsDto'
        },
        warnings: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['manifest', 'willCreate', 'willUpgrade', 'declared', 'files', 'warnings']
} as const;

export const InstallResultDtoSchema = {
    type: 'object',
    properties: {
        templateId: {
            type: 'string'
        },
        templateName: {
            type: 'string'
        },
        filesUploaded: {
            type: 'number'
        },
        scenariosSeeded: {
            type: 'number'
        },
        mcpAttached: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        skillsAttached: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        unresolvedMcp: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        unresolvedSkills: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        warnings: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['templateId', 'templateName', 'filesUploaded', 'scenariosSeeded', 'mcpAttached', 'skillsAttached', 'unresolvedMcp', 'unresolvedSkills', 'warnings']
} as const;

export const InstallFromGitDtoSchema = {
    type: 'object',
    properties: {
        gitUrl: {
            type: 'string',
            description: 'Git URL — https://, http://, git@host:..., or ssh://host/.../repo.git',
            example: 'https://github.com/CleanSlice/agent-templates.git'
        },
        gitRef: {
            type: 'string',
            description: 'Optional ref — branch, tag, or short SHA. Defaults to the remote default branch.',
            example: 'main'
        },
        params: {
            type: 'object',
            description: 'Operator-supplied params (e.g. {"language":"ru"}). Validated against the manifest at install time.',
            additionalProperties: true
        },
        secrets: {
            type: 'object',
            description: 'Operator-supplied secrets (e.g. {"MCP_RANCH_AUTH":"sk-..."}). Used to resolve $secret:NAME references in the manifest at install time (currently for mcp[].authValue). Never echoed back.',
            additionalProperties: true
        }
    },
    required: ['gitUrl']
} as const;

export const ImportSkillUrlDtoSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string',
            description: 'GitHub URL — folder (tree/<sha>/<path>) or file (blob/<sha>/<path>). The folder must contain a SKILL.md or README.md.',
            example: 'https://github.com/supabase/agent-skills/tree/main/skills/supabase-postgres-best-practices'
        },
        name: {
            type: 'string'
        }
    },
    required: ['url']
} as const;

export const ImportSkillDtoSchema = {
    type: 'object',
    properties: {
        repo: {
            type: 'string',
            example: 'anthropics/skills',
            description: 'GitHub owner/repo as returned by /skills/search'
        },
        path: {
            type: 'string',
            example: 'pdf-skill/SKILL.md',
            description: 'Path to the SKILL.md file inside the repo'
        },
        name: {
            type: 'string',
            description: 'Override the auto-derived slug. Lowercase letters, digits and dashes.'
        }
    },
    required: ['repo', 'path']
} as const;

export const CreateSkillDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'devops',
            description: 'Unique slug — lowercase letters, digits, dashes'
        },
        title: {
            type: 'string',
            example: 'DevOps engineer'
        },
        body: {
            type: 'string',
            description: 'Markdown body of the skill'
        },
        description: {
            type: 'string'
        }
    },
    required: ['name', 'title', 'body']
} as const;

export const UpdateSkillDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'devops',
            description: 'Unique slug — lowercase letters, digits, dashes'
        },
        title: {
            type: 'string',
            example: 'DevOps engineer'
        },
        body: {
            type: 'string',
            description: 'Markdown body of the skill'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreatePaddockScenarioMessageDtoSchema = {
    type: 'object',
    properties: {
        text: {
            type: 'string'
        },
        from: {
            type: 'string'
        },
        delayMs: {
            type: 'number'
        }
    },
    required: ['text', 'from']
} as const;

export const CreatePaddockSuccessCriterionDtoSchema = {
    type: 'object',
    properties: {
        dimension: {
            type: 'string',
            enum: ['correctness', 'tool_usage', 'soul_compliance', 'response_quality', 'error_handling']
        },
        description: {
            type: 'string'
        },
        weight: {
            type: 'number'
        }
    },
    required: ['dimension', 'description', 'weight']
} as const;

export const CreatePaddockScenarioSetupDtoSchema = {
    type: 'object',
    properties: {
        files: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        },
        env: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        },
        tools: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const CreatePaddockScenarioDtoSchema = {
    type: 'object',
    properties: {
        templateId: {
            type: 'string',
            nullable: true
        },
        agentId: {
            type: 'string',
            nullable: true
        },
        category: {
            type: 'string',
            enum: ['tool_use', 'memory', 'conversation', 'patching_workflow', 'edge_case', 'multi_turn', 'error_recovery']
        },
        difficulty: {
            type: 'string',
            enum: ['easy', 'medium', 'hard', 'adversarial']
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        expectedBehavior: {
            type: 'string'
        },
        messages: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CreatePaddockScenarioMessageDto'
            }
        },
        successCriteria: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CreatePaddockSuccessCriterionDto'
            }
        },
        setup: {
            nullable: true,
            allOf: [
                {
                    '$ref': '#/components/schemas/CreatePaddockScenarioSetupDto'
                }
            ]
        }
    },
    required: ['category', 'difficulty', 'name', 'description', 'expectedBehavior', 'messages', 'successCriteria']
} as const;

export const GeneratePaddockScenarioDtoSchema = {
    type: 'object',
    properties: {
        description: {
            type: 'string',
            description: 'Free-form description of the problem / behavior the user wants to test.'
        },
        templateId: {
            type: 'string',
            nullable: true
        },
        agentId: {
            type: 'string',
            nullable: true
        },
        category: {
            type: 'string',
            enum: ['tool_use', 'memory', 'conversation', 'patching_workflow', 'edge_case', 'multi_turn', 'error_recovery']
        },
        difficulty: {
            type: 'string',
            enum: ['easy', 'medium', 'hard', 'adversarial']
        },
        credentialId: {
            type: 'string',
            description: 'Optional LlmCredential id; if omitted, the first active Anthropic credential is used.'
        }
    },
    required: ['description']
} as const;

export const UpdatePaddockScenarioDtoSchema = {
    type: 'object',
    properties: {
        category: {
            type: 'string',
            enum: ['tool_use', 'memory', 'conversation', 'patching_workflow', 'edge_case', 'multi_turn', 'error_recovery']
        },
        difficulty: {
            type: 'string',
            enum: ['easy', 'medium', 'hard', 'adversarial']
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        expectedBehavior: {
            type: 'string'
        },
        messages: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CreatePaddockScenarioMessageDto'
            }
        },
        successCriteria: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CreatePaddockSuccessCriterionDto'
            }
        },
        setup: {
            nullable: true,
            allOf: [
                {
                    '$ref': '#/components/schemas/CreatePaddockScenarioSetupDto'
                }
            ]
        }
    }
} as const;

export const SecretEntryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'user-abc/openai_api_key'
        },
        value: {
            type: 'string',
            example: 'sk-...'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: ['name', 'value', 'updatedAt']
} as const;

export const SecretListDtoSchema = {
    type: 'object',
    properties: {
        provider: {
            type: 'string',
            enum: ['aws', 'file'],
            example: 'file'
        },
        secrets: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SecretEntryDto'
            }
        }
    },
    required: ['provider', 'secrets']
} as const;

export const CreateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        },
        roles: {
            type: 'array',
            example: ['User'],
            items: {
                '$ref': '#/components/schemas/UserRoleTypes'
            }
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UpdateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        },
        status: {
            type: 'string',
            enum: ['active', 'invited', 'disabled']
        }
    }
} as const;

export const UpdateUserRolesDtoSchema = {
    type: 'object',
    properties: {
        roles: {
            type: 'array',
            example: ['User'],
            items: {
                '$ref': '#/components/schemas/UserRoleTypes'
            }
        }
    },
    required: ['roles']
} as const;

export const ReportUsageDtoSchema = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            example: '2026-04-22'
        },
        byModel: {
            type: 'object',
            description: 'Per-model usage. Key is the canonical model name (e.g. claude-sonnet-4-6).',
            example: {
                'claude-sonnet-4-6': {
                    inputTokens: 12345,
                    outputTokens: 6789,
                    callCount: 42
                }
            }
        }
    },
    required: ['date', 'byModel']
} as const;

export const RunPaddockJudgeOverrideDtoSchema = {
    type: 'object',
    properties: {
        credentialIds: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        threshold: {
            type: 'number'
        },
        maxLlmCalls: {
            type: 'number'
        },
        maxTimeMs: {
            type: 'number'
        }
    }
} as const;

export const RunPaddockEvaluationDtoSchema = {
    type: 'object',
    properties: {
        agentId: {
            type: 'string'
        },
        scenarioIds: {
            description: 'Optional subset of scenario IDs. If omitted, runs the agent’s template scenarios merged with agent overrides.',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        judgeOverride: {
            '$ref': '#/components/schemas/RunPaddockJudgeOverrideDto'
        }
    },
    required: ['agentId']
} as const;