// This file is auto-generated by @hey-api/openapi-ts

export const CreateOwnerDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'owner@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UpsertSettingDtoSchema = {
    type: 'object',
    properties: {
        valueType: {
            type: 'string',
            enum: ['string', 'json'],
            default: 'string'
        },
        value: {
            type: 'object',
            description: 'String for valueType=string; any JSON for valueType=json'
        }
    },
    required: ['valueType', 'value']
} as const;

export const CreateTemplateDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        image: {
            type: 'string',
            example: 'ghcr.io/org/agent:latest'
        },
        defaultConfig: {
            type: 'object'
        },
        defaultResources: {
            type: 'object'
        }
    },
    required: ['name', 'description', 'image']
} as const;

export const UpdateTemplateDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        image: {
            type: 'string',
            example: 'ghcr.io/org/agent:latest'
        },
        defaultConfig: {
            type: 'object'
        },
        defaultResources: {
            type: 'object'
        }
    }
} as const;

export const AgentResourcesDtoSchema = {
    type: 'object',
    properties: {
        cpu: {
            type: 'string',
            example: '500m'
        },
        memory: {
            type: 'string',
            example: '512Mi'
        }
    },
    required: ['cpu', 'memory']
} as const;

export const CreateAgentDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        config: {
            type: 'object'
        },
        resources: {
            '$ref': '#/components/schemas/AgentResourcesDto'
        }
    },
    required: ['name', 'templateId']
} as const;

export const UpdateAgentDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        templateId: {
            type: 'string'
        },
        config: {
            type: 'object'
        },
        resources: {
            '$ref': '#/components/schemas/AgentResourcesDto'
        }
    }
} as const;

export const CreateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        },
        role: {
            type: 'string',
            enum: ['owner', 'admin', 'member']
        }
    },
    required: ['name', 'email', 'password']
} as const;

export const UpdateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Jane Doe'
        },
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        },
        role: {
            type: 'string',
            enum: ['owner', 'admin', 'member']
        },
        status: {
            type: 'string',
            enum: ['active', 'invited', 'disabled']
        }
    }
} as const;

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'jane@example.com'
        },
        password: {
            type: 'string',
            example: 'strongPassword1',
            minLength: 8
        }
    },
    required: ['email', 'password']
} as const;

export const BridleTextPartDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['text', 'image', 'file'],
            example: 'text'
        },
        text: {
            type: 'string'
        }
    },
    required: ['type', 'text']
} as const;

export const BridleImagePartDtoSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            enum: ['text', 'image', 'file'],
            example: 'image'
        },
        base64: {
            type: 'string',
            description: 'Base64-encoded image data'
        },
        mediaType: {
            type: 'string',
            description: 'MIME type',
            example: 'image/jpeg'
        }
    },
    required: ['type', 'base64', 'mediaType']
} as const;

export const SendMessageDtoSchema = {
    type: 'object',
    properties: {
        text: {
            type: 'string',
            description: 'Message text (plain-text shorthand)'
        },
        parts: {
            description: 'Rich content parts. If omitted, built from text + images.',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BridleTextPartDto'
            }
        },
        images: {
            description: 'Attached images (legacy — prefer parts)',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BridleImagePartDto'
            }
        }
    },
    required: ['text']
} as const;

export const BridleHealthDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        agentConnected: {
            type: 'boolean',
            description: 'Whether any agent runtime is connected via WebSocket'
        },
        browserClients: {
            type: 'number',
            description: 'Number of browser clients connected'
        }
    },
    required: ['ok', 'agentConnected', 'browserClients']
} as const;

export const BridleBotHealthDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        agentConnected: {
            type: 'boolean',
            description: 'Whether this bot agent is connected via WebSocket'
        },
        browserClients: {
            type: 'number',
            description: 'Number of browser clients connected to this bot'
        },
        botId: {
            type: 'string',
            description: 'Bot identifier'
        }
    },
    required: ['ok', 'agentConnected', 'browserClients', 'botId']
} as const;