// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-axios';
import type { HealthControllerCheckData, InitControllerStatusData, InitControllerInitData, SettingControllerFindAllData, SettingControllerFindByGroupData, SettingControllerRemoveData, SettingControllerFindByKeyData, SettingControllerUpsertData, LlmControllerFindAllData, LlmControllerCreateData, LlmControllerRemoveData, LlmControllerFindByIdData, LlmControllerUpdateData, TemplateControllerFindAllData, TemplateControllerCreateData, TemplateControllerRemoveData, TemplateControllerFindByIdData, TemplateControllerUpdateData, AgentControllerFindAllData, AgentControllerCreateData, AgentControllerRemoveData, AgentControllerFindByIdData, AgentControllerUpdateData, AgentControllerRestartData, LogControllerGetLogsData, UserControllerFindAllData, UserControllerCreateData, UserControllerRemoveData, UserControllerFindByIdData, UserControllerUpdateData, AuthControllerLoginData, SendBridleMessageData, SendBridleMessageSyncData, BridleHealthData, BridleHealthResponse, BridleBotHealthData, BridleBotHealthResponse, ListAgentsData, UsageControllerFindForAgentData, UsageControllerReportData, UsageControllerReportResponse, GetKnowledgesData, CreateKnowledgeData, DeleteKnowledgeData, DeleteKnowledgeResponse, GetKnowledgeData, UpdateKnowledgeData, IndexKnowledgeData, GetKnowledgeRecordsData, GetKnowledgeSourcesData, AddKnowledgeSourceData, DeleteKnowledgeSourceData, DeleteKnowledgeSourceResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class HealthService {
    public static healthControllerCheck<ThrowOnError extends boolean = false>(options?: Options<HealthControllerCheckData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/health',
            ...options
        });
    }
    
}

export class SetupService {
    /**
     * Check whether the system needs initial owner setup
     */
    public static initControllerStatus<ThrowOnError extends boolean = false>(options?: Options<InitControllerStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/setup/status',
            ...options
        });
    }
    
    /**
     * Create the first owner. Fails if one already exists.
     */
    public static initControllerInit<ThrowOnError extends boolean = false>(options: Options<InitControllerInitData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/setup/init',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class SettingsService {
    /**
     * List all settings
     */
    public static settingControllerFindAll<ThrowOnError extends boolean = false>(options?: Options<SettingControllerFindAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/settings',
            ...options
        });
    }
    
    /**
     * List settings in a group
     */
    public static settingControllerFindByGroup<ThrowOnError extends boolean = false>(options: Options<SettingControllerFindByGroupData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/settings/{group}',
            ...options
        });
    }
    
    /**
     * Delete a setting
     */
    public static settingControllerRemove<ThrowOnError extends boolean = false>(options: Options<SettingControllerRemoveData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            url: '/settings/{group}/{name}',
            ...options
        });
    }
    
    /**
     * Get a single setting by group/name
     */
    public static settingControllerFindByKey<ThrowOnError extends boolean = false>(options: Options<SettingControllerFindByKeyData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/settings/{group}/{name}',
            ...options
        });
    }
    
    /**
     * Create or replace a setting
     */
    public static settingControllerUpsert<ThrowOnError extends boolean = false>(options: Options<SettingControllerUpsertData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            url: '/settings/{group}/{name}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class LlmsService {
    /**
     * List all LLM credentials
     */
    public static llmControllerFindAll<ThrowOnError extends boolean = false>(options?: Options<LlmControllerFindAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/llms',
            ...options
        });
    }
    
    /**
     * Create a new LLM credential
     */
    public static llmControllerCreate<ThrowOnError extends boolean = false>(options: Options<LlmControllerCreateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/llms',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete an LLM credential
     */
    public static llmControllerRemove<ThrowOnError extends boolean = false>(options: Options<LlmControllerRemoveData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            url: '/llms/{id}',
            ...options
        });
    }
    
    /**
     * Get LLM credential by ID
     */
    public static llmControllerFindById<ThrowOnError extends boolean = false>(options: Options<LlmControllerFindByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/llms/{id}',
            ...options
        });
    }
    
    /**
     * Update an LLM credential
     */
    public static llmControllerUpdate<ThrowOnError extends boolean = false>(options: Options<LlmControllerUpdateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            url: '/llms/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class TemplatesService {
    /**
     * List all agent templates
     */
    public static templateControllerFindAll<ThrowOnError extends boolean = false>(options?: Options<TemplateControllerFindAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/templates',
            ...options
        });
    }
    
    /**
     * Create a new agent template
     */
    public static templateControllerCreate<ThrowOnError extends boolean = false>(options: Options<TemplateControllerCreateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/templates',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete a template
     */
    public static templateControllerRemove<ThrowOnError extends boolean = false>(options: Options<TemplateControllerRemoveData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            url: '/templates/{id}',
            ...options
        });
    }
    
    /**
     * Get template by ID
     */
    public static templateControllerFindById<ThrowOnError extends boolean = false>(options: Options<TemplateControllerFindByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/templates/{id}',
            ...options
        });
    }
    
    /**
     * Update a template
     */
    public static templateControllerUpdate<ThrowOnError extends boolean = false>(options: Options<TemplateControllerUpdateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            url: '/templates/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class AgentsService {
    /**
     * List all agents
     */
    public static agentControllerFindAll<ThrowOnError extends boolean = false>(options?: Options<AgentControllerFindAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/agents',
            ...options
        });
    }
    
    /**
     * Create and deploy a new agent
     */
    public static agentControllerCreate<ThrowOnError extends boolean = false>(options: Options<AgentControllerCreateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/agents',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Stop and delete an agent
     */
    public static agentControllerRemove<ThrowOnError extends boolean = false>(options: Options<AgentControllerRemoveData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            url: '/agents/{id}',
            ...options
        });
    }
    
    /**
     * Get agent by ID
     */
    public static agentControllerFindById<ThrowOnError extends boolean = false>(options: Options<AgentControllerFindByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/agents/{id}',
            ...options
        });
    }
    
    /**
     * Update agent configuration
     */
    public static agentControllerUpdate<ThrowOnError extends boolean = false>(options: Options<AgentControllerUpdateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            url: '/agents/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Restart an agent
     */
    public static agentControllerRestart<ThrowOnError extends boolean = false>(options: Options<AgentControllerRestartData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/agents/{id}/restart',
            ...options
        });
    }
    
}

export class LogsService {
    /**
     * Get agent pod logs
     */
    public static logControllerGetLogs<ThrowOnError extends boolean = false>(options: Options<LogControllerGetLogsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/agents/{agentId}/logs',
            ...options
        });
    }
    
}

export class UsersService {
    /**
     * List all users
     */
    public static userControllerFindAll<ThrowOnError extends boolean = false>(options?: Options<UserControllerFindAllData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/users',
            ...options
        });
    }
    
    /**
     * Invite a new user
     */
    public static userControllerCreate<ThrowOnError extends boolean = false>(options: Options<UserControllerCreateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/users',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Remove user
     */
    public static userControllerRemove<ThrowOnError extends boolean = false>(options: Options<UserControllerRemoveData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            url: '/users/{id}',
            ...options
        });
    }
    
    /**
     * Get user by ID
     */
    public static userControllerFindById<ThrowOnError extends boolean = false>(options: Options<UserControllerFindByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/users/{id}',
            ...options
        });
    }
    
    /**
     * Update user
     */
    public static userControllerUpdate<ThrowOnError extends boolean = false>(options: Options<UserControllerUpdateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            url: '/users/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class AuthService {
    /**
     * Authenticate and receive an access token
     */
    public static authControllerLogin<ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class BridleService {
    /**
     * Send a message to a bot agent (HTTP fallback — fire & forget)
     */
    public static sendBridleMessage<ThrowOnError extends boolean = false>(options: Options<SendBridleMessageData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/api/agent/{botId}/message',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Send a message and wait for the bot agent response (synchronous)
     */
    public static sendBridleMessageSync<ThrowOnError extends boolean = false>(options: Options<SendBridleMessageSyncData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/api/agent/{botId}/message/sync',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Check overall hub status
     */
    public static bridleHealth<ThrowOnError extends boolean = false>(options?: Options<BridleHealthData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<BridleHealthResponse, unknown, ThrowOnError>({
            url: '/api/agent/health',
            ...options
        });
    }
    
    /**
     * Check bot agent connection status
     */
    public static bridleBotHealth<ThrowOnError extends boolean = false>(options: Options<BridleBotHealthData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<BridleBotHealthResponse, unknown, ThrowOnError>({
            url: '/api/agent/{botId}/health',
            ...options
        });
    }
    
    /**
     * List all connected agents
     */
    public static listAgents<ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/api/agent/list',
            ...options
        });
    }
    
}

export class UsageService {
    /**
     * Get 30-day usage for an agent with cost
     */
    public static usageControllerFindForAgent<ThrowOnError extends boolean = false>(options: Options<UsageControllerFindForAgentData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/agents/{agentId}/usage',
            ...options
        });
    }
    
    /**
     * Agent reports its usage (mirrors runtime usage.json)
     */
    public static usageControllerReport<ThrowOnError extends boolean = false>(options: Options<UsageControllerReportData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<UsageControllerReportResponse, unknown, ThrowOnError>({
            url: '/agents/{agentId}/usage',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class ReinsService {
    /**
     * List knowledges
     */
    public static getKnowledges<ThrowOnError extends boolean = false>(options?: Options<GetKnowledgesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/knowledges',
            ...options
        });
    }
    
    /**
     * Create knowledge
     */
    public static createKnowledge<ThrowOnError extends boolean = false>(options: Options<CreateKnowledgeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/knowledges',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete knowledge
     */
    public static deleteKnowledge<ThrowOnError extends boolean = false>(options: Options<DeleteKnowledgeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteKnowledgeResponse, unknown, ThrowOnError>({
            url: '/knowledges/{id}',
            ...options
        });
    }
    
    /**
     * Get one knowledge
     */
    public static getKnowledge<ThrowOnError extends boolean = false>(options: Options<GetKnowledgeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/knowledges/{id}',
            ...options
        });
    }
    
    /**
     * Update knowledge
     */
    public static updateKnowledge<ThrowOnError extends boolean = false>(options: Options<UpdateKnowledgeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            url: '/knowledges/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Start indexing
     */
    public static indexKnowledge<ThrowOnError extends boolean = false>(options: Options<IndexKnowledgeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            url: '/knowledges/{id}/index',
            ...options
        });
    }
    
    /**
     * Query knowledge
     */
    public static getKnowledgeRecords<ThrowOnError extends boolean = false>(options: Options<GetKnowledgeRecordsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/knowledges/{id}/records',
            ...options
        });
    }
    
    /**
     * List sources
     */
    public static getKnowledgeSources<ThrowOnError extends boolean = false>(options: Options<GetKnowledgeSourcesData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            url: '/knowledges/{id}/sources',
            ...options
        });
    }
    
    /**
     * Add source (file|url|text)
     */
    public static addKnowledgeSource<ThrowOnError extends boolean = false>(options: Options<AddKnowledgeSourceData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            ...formDataBodySerializer,
            url: '/knowledges/{id}/sources',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete source
     */
    public static deleteKnowledgeSource<ThrowOnError extends boolean = false>(options: Options<DeleteKnowledgeSourceData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteKnowledgeSourceResponse, unknown, ThrowOnError>({
            url: '/knowledges/{id}/sources/{sourceId}',
            ...options
        });
    }
    
}