// This file is auto-generated by @hey-api/openapi-ts

export type CreateOwnerDto = {
  name: string;
  email: string;
  password: string;
};

export type UpsertSettingDto = {
  valueType: "string" | "json";
  /**
   * String for valueType=string; any JSON for valueType=json
   */
  value: {
    [key: string]: unknown;
  };
};

export type CreateLlmCredentialDto = {
  provider: string;
  model: string;
  apiKey: string;
  fallbackModel?: string;
  label?: string;
  status?: "active" | "disabled";
};

export type UpdateLlmCredentialDto = {
  provider?: string;
  model?: string;
  apiKey?: string;
  fallbackModel?: string;
  label?: string;
  status?: "active" | "disabled";
};

export type CreateTemplateDto = {
  name: string;
  description: string;
  image: string;
  defaultConfig?: {
    [key: string]: unknown;
  };
  defaultResources?: {
    [key: string]: unknown;
  };
};

export type UpdateTemplateDto = {
  name?: string;
  description?: string;
  image?: string;
  defaultConfig?: {
    [key: string]: unknown;
  };
  defaultResources?: {
    [key: string]: unknown;
  };
};

export type SetTemplateSkillsDto = {
  /**
   * Full list of skill IDs to attach. Replaces any prior set.
   */
  skillIds: Array<string>;
};

export type SetTemplateMcpsDto = {
  /**
   * Full list of MCP server IDs to attach. Replaces any prior set.
   */
  mcpServerIds: Array<string>;
};

export type CreateMcpServerDto = {
  name: string;
  description?: {
    [key: string]: unknown;
  };
  url: string;
  transport?: "streamableHttp" | "sse";
  authType?: "none" | "bearer" | "header";
  authValue?: {
    [key: string]: unknown;
  };
  enabled?: boolean;
};

export type UpdateMcpServerDto = {
  name?: string;
  description?: {
    [key: string]: unknown;
  };
  url?: string;
  transport?: "streamableHttp" | "sse";
  authType?: "none" | "bearer" | "header";
  authValue?: {
    [key: string]: unknown;
  };
  enabled?: boolean;
};

export type LoginDto = {
  email: string;
  password: string;
};

export type RegisterDto = {
  name: string;
  email: string;
  password: string;
};

export type SaveTemplateFileDto = {
  /**
   * Full file content as text
   */
  content: string;
};

export type AgentPodStatusDto = {
  agentId: string;
  podName: string;
  phase: "Pending" | "Running" | "Succeeded" | "Failed" | "Unknown";
  ready: boolean;
  restartCount: number;
  startedAt: string | null;
  lastTerminationReason: string | null;
  containerWaitingReason: string | null;
  message: string | null;
  observedAt: string;
};

export type AgentStatusDto = {
  /**
   * Agent DB record (id, name, status, etc.)
   */
  agent: {
    [key: string]: unknown;
  };
  /**
   * Live pod status; null if no pod is currently running for this agent.
   */
  pod: AgentPodStatusDto | null;
};

export type AgentMcpDto = {
  /**
   * Unique MCP server name (key in the runtime registry).
   */
  name: string;
  /**
   * Transport protocol the runtime should use to connect.
   */
  transport: "streamableHttp" | "sse";
  /**
   * MCP server endpoint URL.
   */
  url: string;
  /**
   * Auth scheme for the connection.
   */
  authType: "none" | "bearer" | "header";
  /**
   * Auth credential. For `bearer`: raw token (runtime adds the `Bearer ` prefix). For `header`: literal `Header-Name: value` line. `null` when authType is `none`.
   */
  authValue: string | null;
  /**
   * Always `true` in this list — disabled servers are filtered server-side. Kept for forward compatibility.
   */
  enabled: boolean;
};

export type AgentResourcesDto = {
  cpu: string;
  memory: string;
};

export type CreateAgentDto = {
  name: string;
  templateId: string;
  llmCredentialId?: string;
  config?: {
    [key: string]: unknown;
  };
  resources?: AgentResourcesDto;
  /**
   * When true, the agent is visible on the public landing page to unauthenticated visitors.
   */
  isPublic?: boolean;
  /**
   * When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.
   */
  isAdmin?: boolean;
};

export type UpdateAgentDto = {
  name?: string;
  templateId?: string;
  llmCredentialId?: string;
  config?: {
    [key: string]: unknown;
  };
  resources?: AgentResourcesDto;
  /**
   * When true, the agent is visible on the public landing page to unauthenticated visitors.
   */
  isPublic?: boolean;
  /**
   * When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.
   */
  isAdmin?: boolean;
};

export type SetAgentDebugDto = {
  /**
   * When true, runtime emits prompt-debug snapshots over the bridle WS to admin clients.
   */
  enabled: boolean;
};

export type SaveFileDto = {
  /**
   * Full file content as text
   */
  content: string;
};

export type BridleTextPartDto = {
  type: "text" | "image" | "file";
  text: string;
};

export type BridleImagePartDto = {
  type: "text" | "image" | "file";
  /**
   * Base64-encoded image data
   */
  base64: string;
  /**
   * MIME type
   */
  mediaType: string;
};

export type SendMessageDto = {
  /**
   * Message text (plain-text shorthand)
   */
  text: string;
  /**
   * Rich content parts. If omitted, built from text + images.
   */
  parts?: Array<BridleTextPartDto>;
  /**
   * Attached images (legacy — prefer parts)
   */
  images?: Array<BridleImagePartDto>;
};

export type BridleHealthDto = {
  ok: boolean;
  /**
   * Whether any agent runtime is connected via WebSocket
   */
  agentConnected: boolean;
  /**
   * Number of browser clients connected
   */
  browserClients: number;
};

export type BridleBotHealthDto = {
  ok: boolean;
  /**
   * Whether this bot agent is connected via WebSocket
   */
  agentConnected: boolean;
  /**
   * Number of browser clients connected to this bot
   */
  browserClients: number;
  /**
   * Bot identifier
   */
  botId: string;
};

export type TranscriptMessageDto = {
  id: string;
  role: "user" | "assistant";
  text: string;
  /**
   * Unix epoch milliseconds.
   */
  ts: number;
};

export type TranscriptResponseDto = {
  messages: Array<TranscriptMessageDto>;
  /**
   * Channel the transcript was loaded from.
   */
  channel: string;
};

export type SecretEntryDto = {
  name: string;
  value: string;
  updatedAt: string | null;
};

export type SecretListDto = {
  provider: "aws" | "file";
  secrets: Array<SecretEntryDto>;
};

export enum UserRoleTypes {
  OWNER = "Owner",
  ADMIN = "Admin",
  USER = "User",
  AGENT = "Agent",
}

export type CreateUserDto = {
  name: string;
  email: string;
  password: string;
  roles?: Array<UserRoleTypes>;
};

export type UpdateUserDto = {
  name?: string;
  email?: string;
  password?: string;
  status?: "active" | "invited" | "disabled";
};

export type UpdateUserRolesDto = {
  roles: Array<UserRoleTypes>;
};

export type ReportUsageDto = {
  date: string;
  /**
   * Per-model usage. Key is the canonical model name (e.g. claude-sonnet-4-6).
   */
  byModel: {
    [key: string]: unknown;
  };
};

export type GraphNodeDto = {
  id: string;
  label: string;
  entityType: string;
  description: string;
};

export type GraphEdgeDto = {
  id: string;
  source: string;
  target: string;
  weight: number;
  keywords: string;
  description: string;
};

export type GraphDto = {
  nodes: Array<GraphNodeDto>;
  edges: Array<GraphEdgeDto>;
  isTruncated: boolean;
};

export type CreateKnowledgeDto = {
  name: string;
  description?: string;
  entityTypes?: Array<string>;
  relationshipTypes?: Array<string>;
};

export type UpdateKnowledgeDto = {
  name?: string;
  description?: string | null;
  entityTypes?: Array<string>;
  relationshipTypes?: Array<string>;
};

export type QueryKnowledgeDto = {
  query: string;
  mode?: "hybrid" | "local" | "global" | "naive";
  topK?: number;
};

export type KnowledgeQueryReferenceDto = {
  referenceId: string;
  filePath: string;
};

export type KnowledgeQueryResultDto = {
  answer: string;
  references: Array<KnowledgeQueryReferenceDto>;
};

export type CreateSourceDto = {
  type: "file" | "url" | "text";
  name: string;
  url?: string;
  content?: string;
};

export type ImportSkillUrlDto = {
  /**
   * GitHub URL — folder (tree/<sha>/<path>) or file (blob/<sha>/<path>). The folder must contain a SKILL.md or README.md.
   */
  url: string;
  name?: string;
};

export type ImportSkillDto = {
  /**
   * GitHub owner/repo as returned by /skills/search
   */
  repo: string;
  /**
   * Path to the SKILL.md file inside the repo
   */
  path: string;
  /**
   * Override the auto-derived slug. Lowercase letters, digits and dashes.
   */
  name?: string;
};

export type CreateSkillDto = {
  /**
   * Unique slug — lowercase letters, digits, dashes
   */
  name: string;
  title: string;
  /**
   * Markdown body of the skill
   */
  body: string;
  description?: string;
};

export type UpdateSkillDto = {
  /**
   * Unique slug — lowercase letters, digits, dashes
   */
  name?: string;
  title?: string;
  /**
   * Markdown body of the skill
   */
  body?: string;
  description?: string;
};

export type CreatePaddockScenarioMessageDto = {
  text: string;
  from: string;
  delayMs?: number;
};

export type CreatePaddockSuccessCriterionDto = {
  dimension:
    | "correctness"
    | "tool_usage"
    | "soul_compliance"
    | "response_quality"
    | "error_handling";
  description: string;
  weight: number;
};

export type CreatePaddockScenarioSetupDto = {
  files?: {
    [key: string]: string;
  };
  env?: {
    [key: string]: string;
  };
  tools?: Array<string>;
};

export type CreatePaddockScenarioDto = {
  templateId?: string | null;
  agentId?: string | null;
  category:
    | "tool_use"
    | "memory"
    | "conversation"
    | "patching_workflow"
    | "edge_case"
    | "multi_turn"
    | "error_recovery";
  difficulty: "easy" | "medium" | "hard" | "adversarial";
  name: string;
  description: string;
  expectedBehavior: string;
  messages: Array<CreatePaddockScenarioMessageDto>;
  successCriteria: Array<CreatePaddockSuccessCriterionDto>;
  setup?: CreatePaddockScenarioSetupDto | null;
};

export type GeneratePaddockScenarioDto = {
  /**
   * Free-form description of the problem / behavior the user wants to test.
   */
  description: string;
  templateId?: string | null;
  agentId?: string | null;
  category?:
    | "tool_use"
    | "memory"
    | "conversation"
    | "patching_workflow"
    | "edge_case"
    | "multi_turn"
    | "error_recovery";
  difficulty?: "easy" | "medium" | "hard" | "adversarial";
  /**
   * Optional LlmCredential id; if omitted, the first active Anthropic credential is used.
   */
  credentialId?: string;
};

export type UpdatePaddockScenarioDto = {
  category?:
    | "tool_use"
    | "memory"
    | "conversation"
    | "patching_workflow"
    | "edge_case"
    | "multi_turn"
    | "error_recovery";
  difficulty?: "easy" | "medium" | "hard" | "adversarial";
  name?: string;
  description?: string;
  expectedBehavior?: string;
  messages?: Array<CreatePaddockScenarioMessageDto>;
  successCriteria?: Array<CreatePaddockSuccessCriterionDto>;
  setup?: CreatePaddockScenarioSetupDto | null;
};

export type RunPaddockJudgeOverrideDto = {
  credentialIds?: Array<string>;
  threshold?: number;
  maxLlmCalls?: number;
  maxTimeMs?: number;
};

export type RunPaddockEvaluationDto = {
  agentId: string;
  /**
   * Optional subset of scenario IDs. If omitted, runs the agent’s template scenarios merged with agent overrides.
   */
  scenarioIds?: Array<string>;
  judgeOverride?: RunPaddockJudgeOverrideDto;
};

export type HealthControllerCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthControllerCheckResponses = {
  200: unknown;
};

export type InitControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/setup/status";
};

export type InitControllerStatusResponses = {
  200: unknown;
};

export type InitControllerInitData = {
  body: CreateOwnerDto;
  path?: never;
  query?: never;
  url: "/setup/init";
};

export type InitControllerInitResponses = {
  201: unknown;
};

export type SettingControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/settings";
};

export type SettingControllerFindAllResponses = {
  200: unknown;
};

export type SettingControllerFindByGroupData = {
  body?: never;
  path: {
    group: string;
  };
  query?: never;
  url: "/settings/{group}";
};

export type SettingControllerFindByGroupResponses = {
  200: unknown;
};

export type SettingControllerRemoveData = {
  body?: never;
  path: {
    group: string;
    name: string;
  };
  query?: never;
  url: "/settings/{group}/{name}";
};

export type SettingControllerRemoveResponses = {
  200: unknown;
};

export type SettingControllerFindByKeyData = {
  body?: never;
  path: {
    group: string;
    name: string;
  };
  query?: never;
  url: "/settings/{group}/{name}";
};

export type SettingControllerFindByKeyResponses = {
  200: unknown;
};

export type SettingControllerUpsertData = {
  body: UpsertSettingDto;
  path: {
    group: string;
    name: string;
  };
  query?: never;
  url: "/settings/{group}/{name}";
};

export type SettingControllerUpsertResponses = {
  200: unknown;
};

export type LlmControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/llms";
};

export type LlmControllerFindAllResponses = {
  200: unknown;
};

export type LlmControllerCreateData = {
  body: CreateLlmCredentialDto;
  path?: never;
  query?: never;
  url: "/llms";
};

export type LlmControllerCreateResponses = {
  201: unknown;
};

export type LlmControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}";
};

export type LlmControllerRemoveResponses = {
  200: unknown;
};

export type LlmControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}";
};

export type LlmControllerFindByIdResponses = {
  200: unknown;
};

export type LlmControllerUpdateData = {
  body: UpdateLlmCredentialDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}";
};

export type LlmControllerUpdateResponses = {
  200: unknown;
};

export type TemplateControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/templates";
};

export type TemplateControllerFindAllResponses = {
  200: unknown;
};

export type TemplateControllerCreateData = {
  body: CreateTemplateDto;
  path?: never;
  query?: never;
  url: "/templates";
};

export type TemplateControllerCreateResponses = {
  201: unknown;
};

export type TemplateControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}";
};

export type TemplateControllerRemoveResponses = {
  200: unknown;
};

export type TemplateControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}";
};

export type TemplateControllerFindByIdResponses = {
  200: unknown;
};

export type TemplateControllerUpdateData = {
  body: UpdateTemplateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}";
};

export type TemplateControllerUpdateResponses = {
  200: unknown;
};

export type TemplateControllerSetSkillsData = {
  body: SetTemplateSkillsDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/skills";
};

export type TemplateControllerSetSkillsResponses = {
  200: unknown;
};

export type TemplateControllerSetMcpsData = {
  body: SetTemplateMcpsDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/mcps";
};

export type TemplateControllerSetMcpsResponses = {
  200: unknown;
};

export type McpServerControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp-servers";
};

export type McpServerControllerFindAllResponses = {
  200: unknown;
};

export type McpServerControllerCreateData = {
  body: CreateMcpServerDto;
  path?: never;
  query?: never;
  url: "/mcp-servers";
};

export type McpServerControllerCreateResponses = {
  201: unknown;
};

export type McpServerControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/mcp-servers/{id}";
};

export type McpServerControllerRemoveResponses = {
  200: unknown;
};

export type McpServerControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/mcp-servers/{id}";
};

export type McpServerControllerFindByIdResponses = {
  200: unknown;
};

export type McpServerControllerUpdateData = {
  body: UpdateMcpServerDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/mcp-servers/{id}";
};

export type McpServerControllerUpdateResponses = {
  200: unknown;
};

export type AuthControllerLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type AuthControllerLoginResponses = {
  200: unknown;
};

export type AuthControllerRegisterData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthControllerRegisterResponses = {
  200: unknown;
};

export type AuthControllerMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type AuthControllerMeResponses = {
  200: unknown;
};

export type TemplateFileControllerListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/files";
};

export type TemplateFileControllerListResponses = {
  200: unknown;
};

export type TemplateFileControllerReadData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    path: string;
  };
  url: "/templates/{id}/files/content";
};

export type TemplateFileControllerReadResponses = {
  200: unknown;
};

export type TemplateFileControllerSaveData = {
  body: SaveTemplateFileDto;
  path: {
    id: string;
  };
  query: {
    path: string;
  };
  url: "/templates/{id}/files/content";
};

export type TemplateFileControllerSaveResponses = {
  200: unknown;
};

export type TemplateFileControllerUploadData = {
  body: {
    files?: Array<Blob | File>;
    /**
     * Relative paths matching files[] by index, e.g. ".agent/agent.md"
     */
    paths?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/files/upload";
};

export type TemplateFileControllerUploadResponses = {
  201: unknown;
};

export type AgentControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents";
};

export type AgentControllerFindAllResponses = {
  200: unknown;
};

export type AgentControllerCreateData = {
  body: CreateAgentDto;
  path?: never;
  query?: never;
  url: "/agents";
};

export type AgentControllerCreateResponses = {
  201: unknown;
};

export type AgentControllerFindPublicData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/public";
};

export type AgentControllerFindPublicResponses = {
  200: unknown;
};

export type AgentControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/status";
};

export type AgentControllerStatusResponses = {
  200: Array<AgentStatusDto>;
};

export type AgentControllerStatusResponse =
  AgentControllerStatusResponses[keyof AgentControllerStatusResponses];

export type AgentControllerStatusStreamData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/status/stream";
};

export type AgentControllerStatusStreamResponses = {
  200: unknown;
};

export type AgentControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}";
};

export type AgentControllerRemoveResponses = {
  200: unknown;
};

export type AgentControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}";
};

export type AgentControllerFindByIdResponses = {
  200: unknown;
};

export type AgentControllerUpdateData = {
  body: UpdateAgentDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}";
};

export type AgentControllerUpdateResponses = {
  200: unknown;
};

export type GetAgentMcpsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/mcps";
};

export type GetAgentMcpsResponses = {
  200: Array<AgentMcpDto>;
};

export type GetAgentMcpsResponse =
  GetAgentMcpsResponses[keyof GetAgentMcpsResponses];

export type AgentControllerSetDebugData = {
  body: SetAgentDebugDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/debug";
};

export type AgentControllerSetDebugResponses = {
  200: unknown;
};

export type AgentControllerFindAdminData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/admin/current";
};

export type AgentControllerFindAdminResponses = {
  200: unknown;
};

export type AgentControllerDemoteAdminData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/promote-admin";
};

export type AgentControllerDemoteAdminResponses = {
  200: unknown;
};

export type AgentControllerPromoteAdminData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/promote-admin";
};

export type AgentControllerPromoteAdminResponses = {
  201: unknown;
};

export type AgentControllerRestartData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/restart";
};

export type AgentControllerRestartResponses = {
  201: unknown;
};

export type FileControllerListData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/files";
};

export type FileControllerListResponses = {
  200: unknown;
};

export type FileControllerReadData = {
  body?: never;
  path: {
    agentId: string;
  };
  query: {
    path: string;
  };
  url: "/agents/{agentId}/files/content";
};

export type FileControllerReadResponses = {
  200: unknown;
};

export type FileControllerSaveData = {
  body: SaveFileDto;
  path: {
    agentId: string;
  };
  query: {
    path: string;
  };
  url: "/agents/{agentId}/files/content";
};

export type FileControllerSaveResponses = {
  200: unknown;
};

export type FileControllerSyncData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/files/sync";
};

export type FileControllerSyncResponses = {
  200: unknown;
};

export type SendBridleMessageData = {
  body: SendMessageDto;
  path: {
    botId: string;
  };
  query?: never;
  url: "/api/agent/{botId}/message";
};

export type SendBridleMessageResponses = {
  200: unknown;
};

export type SendBridleMessageSyncData = {
  body: SendMessageDto;
  path: {
    botId: string;
  };
  query?: never;
  url: "/api/agent/{botId}/message/sync";
};

export type SendBridleMessageSyncResponses = {
  200: unknown;
};

export type BridleHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/agent/health";
};

export type BridleHealthResponses = {
  200: BridleHealthDto;
};

export type BridleHealthResponse =
  BridleHealthResponses[keyof BridleHealthResponses];

export type BridleBotHealthData = {
  body?: never;
  path: {
    botId: string;
  };
  query?: never;
  url: "/api/agent/{botId}/health";
};

export type BridleBotHealthResponses = {
  200: BridleBotHealthDto;
};

export type BridleBotHealthResponse =
  BridleBotHealthResponses[keyof BridleBotHealthResponses];

export type ListAgentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/agent/list";
};

export type ListAgentsResponses = {
  200: unknown;
};

export type ResetBridleTranscriptData = {
  body?: never;
  path: {
    botId: string;
  };
  query?: {
    /**
     * Session channel — defaults to "admin".
     */
    channel?: string;
  };
  url: "/api/agent/{botId}/transcript";
};

export type ResetBridleTranscriptResponses = {
  204: void;
};

export type ResetBridleTranscriptResponse =
  ResetBridleTranscriptResponses[keyof ResetBridleTranscriptResponses];

export type GetBridleTranscriptData = {
  body?: never;
  path: {
    botId: string;
  };
  query?: {
    /**
     * Session channel — defaults to "admin" for the admin app.
     */
    channel?: string;
  };
  url: "/api/agent/{botId}/transcript";
};

export type GetBridleTranscriptResponses = {
  200: TranscriptResponseDto;
};

export type GetBridleTranscriptResponse =
  GetBridleTranscriptResponses[keyof GetBridleTranscriptResponses];

export type SecretControllerListData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/secrets";
};

export type SecretControllerListResponses = {
  200: SecretListDto;
};

export type SecretControllerListResponse =
  SecretControllerListResponses[keyof SecretControllerListResponses];

export type LogControllerGetLogsData = {
  body?: never;
  path: {
    agentId: string;
  };
  query: {
    tail: string;
  };
  url: "/agents/{agentId}/logs";
};

export type LogControllerGetLogsResponses = {
  200: unknown;
};

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type UserControllerFindAllResponses = {
  200: unknown;
};

export type UserControllerCreateData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: "/users";
};

export type UserControllerCreateResponses = {
  201: unknown;
};

export type UserControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerRemoveResponses = {
  200: unknown;
};

export type UserControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerFindByIdResponses = {
  200: unknown;
};

export type UserControllerUpdateData = {
  body: UpdateUserDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerUpdateResponses = {
  200: unknown;
};

export type UserControllerUpdateRolesData = {
  body: UpdateUserRolesDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}/roles";
};

export type UserControllerUpdateRolesResponses = {
  200: unknown;
};

export type UsageControllerFindForAgentData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/usage";
};

export type UsageControllerFindForAgentResponses = {
  200: unknown;
};

export type UsageControllerReportData = {
  body: ReportUsageDto;
  headers: {
    "x-bridle-api-key": string;
  };
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/usage";
};

export type UsageControllerReportResponses = {
  204: void;
};

export type UsageControllerReportResponse =
  UsageControllerReportResponses[keyof UsageControllerReportResponses];

export type GetKnowledgesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/knowledges";
};

export type GetKnowledgesResponses = {
  200: unknown;
};

export type CreateKnowledgeData = {
  body: CreateKnowledgeDto;
  path?: never;
  query?: never;
  url: "/knowledges";
};

export type CreateKnowledgeResponses = {
  201: unknown;
};

export type GetGraphLabelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/knowledges/graph/labels";
};

export type GetGraphLabelsResponses = {
  200: unknown;
};

export type GetGraphData = {
  body?: never;
  path?: never;
  query: {
    label: string;
    maxDepth?: number;
    maxNodes?: number;
  };
  url: "/knowledges/graph";
};

export type GetGraphResponses = {
  200: GraphDto;
};

export type GetGraphResponse = GetGraphResponses[keyof GetGraphResponses];

export type DeleteKnowledgeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}";
};

export type DeleteKnowledgeResponses = {
  204: void;
};

export type DeleteKnowledgeResponse =
  DeleteKnowledgeResponses[keyof DeleteKnowledgeResponses];

export type GetKnowledgeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}";
};

export type GetKnowledgeResponses = {
  200: unknown;
};

export type UpdateKnowledgeData = {
  body: UpdateKnowledgeDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}";
};

export type UpdateKnowledgeResponses = {
  200: unknown;
};

export type IndexKnowledgeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}/index";
};

export type IndexKnowledgeResponses = {
  202: unknown;
};

export type QueryKnowledgeData = {
  body: QueryKnowledgeDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}/query";
};

export type QueryKnowledgeResponses = {
  200: KnowledgeQueryResultDto;
};

export type QueryKnowledgeResponse =
  QueryKnowledgeResponses[keyof QueryKnowledgeResponses];

export type GetKnowledgeSourcesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}/sources";
};

export type GetKnowledgeSourcesResponses = {
  200: unknown;
};

export type AddKnowledgeSourceData = {
  body: CreateSourceDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}/sources";
};

export type AddKnowledgeSourceResponses = {
  201: unknown;
};

export type DeleteKnowledgeSourceData = {
  body?: never;
  path: {
    id: string;
    sourceId: string;
  };
  query?: never;
  url: "/knowledges/{id}/sources/{sourceId}";
};

export type DeleteKnowledgeSourceResponses = {
  204: void;
};

export type DeleteKnowledgeSourceResponse =
  DeleteKnowledgeSourceResponses[keyof DeleteKnowledgeSourceResponses];

export type SkillControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/skills";
};

export type SkillControllerFindAllResponses = {
  200: unknown;
};

export type SkillControllerCreateData = {
  body: CreateSkillDto;
  path?: never;
  query?: never;
  url: "/skills";
};

export type SkillControllerCreateResponses = {
  201: unknown;
};

export type SkillControllerListSourcesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/skills/sources";
};

export type SkillControllerListSourcesResponses = {
  200: unknown;
};

export type SkillControllerSearchData = {
  body?: never;
  path?: never;
  query: {
    q: string;
  };
  url: "/skills/search";
};

export type SkillControllerSearchResponses = {
  200: unknown;
};

export type SkillControllerImportFromUrlData = {
  body: ImportSkillUrlDto;
  path?: never;
  query?: never;
  url: "/skills/import-url";
};

export type SkillControllerImportFromUrlResponses = {
  201: unknown;
};

export type SkillControllerImportFromGithubData = {
  body: ImportSkillDto;
  path?: never;
  query?: never;
  url: "/skills/import";
};

export type SkillControllerImportFromGithubResponses = {
  201: unknown;
};

export type SkillControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}";
};

export type SkillControllerRemoveResponses = {
  200: unknown;
};

export type SkillControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}";
};

export type SkillControllerFindByIdResponses = {
  200: unknown;
};

export type SkillControllerUpdateData = {
  body: UpdateSkillDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}";
};

export type SkillControllerUpdateResponses = {
  200: unknown;
};

export type RancherControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/rancher/status";
};

export type RancherControllerStatusResponses = {
  200: unknown;
};

export type RancherControllerEnsureTemplateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/rancher/template";
};

export type RancherControllerEnsureTemplateResponses = {
  201: unknown;
};

export type PaddockScenarioControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    templateId?: string;
    agentId?: string;
  };
  url: "/paddock-scenarios";
};

export type PaddockScenarioControllerFindAllResponses = {
  200: unknown;
};

export type PaddockScenarioControllerCreateData = {
  body: CreatePaddockScenarioDto;
  path?: never;
  query?: never;
  url: "/paddock-scenarios";
};

export type PaddockScenarioControllerCreateResponses = {
  201: unknown;
};

export type PaddockScenarioControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-scenarios/{id}";
};

export type PaddockScenarioControllerRemoveResponses = {
  200: unknown;
};

export type PaddockScenarioControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-scenarios/{id}";
};

export type PaddockScenarioControllerFindByIdResponses = {
  200: unknown;
};

export type PaddockScenarioControllerUpdateData = {
  body: UpdatePaddockScenarioDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-scenarios/{id}";
};

export type PaddockScenarioControllerUpdateResponses = {
  200: unknown;
};

export type PaddockScenarioControllerGenerateData = {
  body: GeneratePaddockScenarioDto;
  path?: never;
  query?: never;
  url: "/paddock-scenarios/generate";
};

export type PaddockScenarioControllerGenerateResponses = {
  201: unknown;
};

export type PaddockEvaluationControllerListData = {
  body?: never;
  path?: never;
  query?: {
    agentId?: string;
    templateId?: string;
    limit?: string;
  };
  url: "/paddock-evaluations";
};

export type PaddockEvaluationControllerListResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerStartData = {
  body: RunPaddockEvaluationDto;
  path?: never;
  query?: never;
  url: "/paddock-evaluations";
};

export type PaddockEvaluationControllerStartResponses = {
  201: unknown;
};

export type PaddockEvaluationControllerGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}";
};

export type PaddockEvaluationControllerGetResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerReportData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/report";
};

export type PaddockEvaluationControllerReportResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerTraceData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    scenarioId: string;
  };
  url: "/paddock-evaluations/{id}/trace";
};

export type PaddockEvaluationControllerTraceResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerAbortData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/abort";
};

export type PaddockEvaluationControllerAbortResponses = {
  201: unknown;
};

export type PaddockEvaluationControllerRerunData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/rerun";
};

export type PaddockEvaluationControllerRerunResponses = {
  201: unknown;
};

export type SseControllerSseData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/sse";
};

export type SseControllerSseResponses = {
  200: unknown;
};

export type SseControllerMessagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/messages";
};

export type SseControllerMessagesResponses = {
  201: unknown;
};

export type SseControllerDebugSessionsData = {
  body?: never;
  path: {
    teamId: string;
  };
  query?: never;
  url: "/teams/{teamId}/sessions/debug";
};

export type SseControllerDebugSessionsResponses = {
  200: unknown;
};

export type StreamableHttpControllerHandleDeleteRequestData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/mcp";
};

export type StreamableHttpControllerHandleDeleteRequestResponses = {
  200: unknown;
};

export type StreamableHttpControllerHandleGetRequestData = {
  body?: never;
  path: {
    teamId: string;
  };
  query?: never;
  url: "/mcp/mcp";
};

export type StreamableHttpControllerHandleGetRequestResponses = {
  200: unknown;
};

export type StreamableHttpControllerHandlePostRequestData = {
  body?: never;
  path: {
    teamId: string;
  };
  query?: never;
  url: "/mcp/mcp";
};

export type StreamableHttpControllerHandlePostRequestResponses = {
  201: unknown;
};

export type ClientOptions = {
  baseURL: string;
};
