// This file is auto-generated by @hey-api/openapi-ts

export type CreateOwnerDto = {
    name: string;
    email: string;
    password: string;
};

export type UpsertSettingDto = {
    valueType: 'string' | 'json';
    /**
     * String for valueType=string; any JSON for valueType=json
     */
    value: {
        [key: string]: unknown;
    };
};

export type CreateLlmCredentialDto = {
    provider: string;
    model: string;
    apiKey: string;
    fallbackModel?: string;
    label?: string;
    status?: 'active' | 'disabled';
};

export type UpdateLlmCredentialDto = {
    provider?: string;
    model?: string;
    apiKey?: string;
    fallbackModel?: string;
    label?: string;
    status?: 'active' | 'disabled';
};

export type CreateTemplateDto = {
    name: string;
    description: string;
    image: string;
    defaultConfig?: {
        [key: string]: unknown;
    };
    defaultResources?: {
        [key: string]: unknown;
    };
    defaultKnowledgeIds?: Array<string>;
};

export type UpdateTemplateDto = {
    name?: string;
    description?: string;
    image?: string;
    defaultConfig?: {
        [key: string]: unknown;
    };
    defaultResources?: {
        [key: string]: unknown;
    };
    defaultKnowledgeIds?: Array<string>;
};

export type AgentResourcesDto = {
    cpu: string;
    memory: string;
};

export type CreateAgentDto = {
    name: string;
    templateId: string;
    llmCredentialId?: string;
    config?: {
        [key: string]: unknown;
    };
    resources?: AgentResourcesDto;
};

export type UpdateAgentDto = {
    name?: string;
    templateId?: string;
    llmCredentialId?: string;
    config?: {
        [key: string]: unknown;
    };
    resources?: AgentResourcesDto;
};

export type SaveFileDto = {
    /**
     * Full file content as text
     */
    content: string;
};

export type CreateUserDto = {
    name: string;
    email: string;
    password: string;
    role?: 'owner' | 'admin' | 'member';
};

export type UpdateUserDto = {
    name?: string;
    email?: string;
    password?: string;
    role?: 'owner' | 'admin' | 'member';
    status?: 'active' | 'invited' | 'disabled';
};

export type LoginDto = {
    email: string;
    password: string;
};

export type BridleTextPartDto = {
    type: 'text' | 'image' | 'file';
    text: string;
};

export type BridleImagePartDto = {
    type: 'text' | 'image' | 'file';
    /**
     * Base64-encoded image data
     */
    base64: string;
    /**
     * MIME type
     */
    mediaType: string;
};

export type SendMessageDto = {
    /**
     * Message text (plain-text shorthand)
     */
    text: string;
    /**
     * Rich content parts. If omitted, built from text + images.
     */
    parts?: Array<BridleTextPartDto>;
    /**
     * Attached images (legacy — prefer parts)
     */
    images?: Array<BridleImagePartDto>;
};

export type BridleHealthDto = {
    ok: boolean;
    /**
     * Whether any agent runtime is connected via WebSocket
     */
    agentConnected: boolean;
    /**
     * Number of browser clients connected
     */
    browserClients: number;
};

export type BridleBotHealthDto = {
    ok: boolean;
    /**
     * Whether this bot agent is connected via WebSocket
     */
    agentConnected: boolean;
    /**
     * Number of browser clients connected to this bot
     */
    browserClients: number;
    /**
     * Bot identifier
     */
    botId: string;
};

export type ReportUsageDto = {
    date: string;
    /**
     * Per-model usage. Key is the canonical model name (e.g. claude-sonnet-4-6).
     */
    byModel: {
        [key: string]: unknown;
    };
};

export type GraphNodeDto = {
    id: string;
    label: string;
    entityType: string;
    description: string;
};

export type GraphEdgeDto = {
    id: string;
    source: string;
    target: string;
    weight: number;
    keywords: string;
    description: string;
};

export type GraphDto = {
    nodes: Array<GraphNodeDto>;
    edges: Array<GraphEdgeDto>;
    isTruncated: boolean;
};

export type CreateKnowledgeDto = {
    name: string;
    description?: string;
    entityTypes?: Array<string>;
    relationshipTypes?: Array<string>;
};

export type UpdateKnowledgeDto = {
    name?: string;
    description?: string | null;
    entityTypes?: Array<string>;
    relationshipTypes?: Array<string>;
};

export type QueryKnowledgeDto = {
    query: string;
    mode?: 'hybrid' | 'local' | 'global' | 'naive';
    topK?: number;
};

export type KnowledgeQueryReferenceDto = {
    referenceId: string;
    filePath: string;
};

export type KnowledgeQueryResultDto = {
    answer: string;
    references: Array<KnowledgeQueryReferenceDto>;
};

export type CreateSourceDto = {
    type: 'file' | 'url' | 'text';
    name: string;
    url?: string;
    content?: string;
};

export type ImportSkillUrlDto = {
    /**
     * GitHub URL — folder (tree/<sha>/<path>) or file (blob/<sha>/<path>). The folder must contain a SKILL.md or README.md.
     */
    url: string;
    name?: string;
};

export type ImportSkillDto = {
    /**
     * GitHub owner/repo as returned by /skills/search
     */
    repo: string;
    /**
     * Path to the SKILL.md file inside the repo
     */
    path: string;
    /**
     * Override the auto-derived slug. Lowercase letters, digits and dashes.
     */
    name?: string;
};

export type CreateSkillDto = {
    /**
     * Unique slug — lowercase letters, digits, dashes
     */
    name: string;
    title: string;
    /**
     * Markdown body of the skill
     */
    body: string;
    description?: string;
};

export type UpdateSkillDto = {
    /**
     * Unique slug — lowercase letters, digits, dashes
     */
    name?: string;
    title?: string;
    /**
     * Markdown body of the skill
     */
    body?: string;
    description?: string;
};

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthControllerCheckResponses = {
    200: unknown;
};

export type InitControllerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/setup/status';
};

export type InitControllerStatusResponses = {
    200: unknown;
};

export type InitControllerInitData = {
    body: CreateOwnerDto;
    path?: never;
    query?: never;
    url: '/setup/init';
};

export type InitControllerInitResponses = {
    201: unknown;
};

export type SettingControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type SettingControllerFindAllResponses = {
    200: unknown;
};

export type SettingControllerFindByGroupData = {
    body?: never;
    path: {
        group: string;
    };
    query?: never;
    url: '/settings/{group}';
};

export type SettingControllerFindByGroupResponses = {
    200: unknown;
};

export type SettingControllerRemoveData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/settings/{group}/{name}';
};

export type SettingControllerRemoveResponses = {
    200: unknown;
};

export type SettingControllerFindByKeyData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/settings/{group}/{name}';
};

export type SettingControllerFindByKeyResponses = {
    200: unknown;
};

export type SettingControllerUpsertData = {
    body: UpsertSettingDto;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/settings/{group}/{name}';
};

export type SettingControllerUpsertResponses = {
    200: unknown;
};

export type LlmControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/llms';
};

export type LlmControllerFindAllResponses = {
    200: unknown;
};

export type LlmControllerCreateData = {
    body: CreateLlmCredentialDto;
    path?: never;
    query?: never;
    url: '/llms';
};

export type LlmControllerCreateResponses = {
    201: unknown;
};

export type LlmControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/llms/{id}';
};

export type LlmControllerRemoveResponses = {
    200: unknown;
};

export type LlmControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/llms/{id}';
};

export type LlmControllerFindByIdResponses = {
    200: unknown;
};

export type LlmControllerUpdateData = {
    body: UpdateLlmCredentialDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/llms/{id}';
};

export type LlmControllerUpdateResponses = {
    200: unknown;
};

export type TemplateControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates';
};

export type TemplateControllerFindAllResponses = {
    200: unknown;
};

export type TemplateControllerCreateData = {
    body: CreateTemplateDto;
    path?: never;
    query?: never;
    url: '/templates';
};

export type TemplateControllerCreateResponses = {
    201: unknown;
};

export type TemplateControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/templates/{id}';
};

export type TemplateControllerRemoveResponses = {
    200: unknown;
};

export type TemplateControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/templates/{id}';
};

export type TemplateControllerFindByIdResponses = {
    200: unknown;
};

export type TemplateControllerUpdateData = {
    body: UpdateTemplateDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/templates/{id}';
};

export type TemplateControllerUpdateResponses = {
    200: unknown;
};

export type AgentControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentControllerFindAllResponses = {
    200: unknown;
};

export type AgentControllerCreateData = {
    body: CreateAgentDto;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentControllerCreateResponses = {
    201: unknown;
};

export type AgentControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentControllerRemoveResponses = {
    200: unknown;
};

export type AgentControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentControllerFindByIdResponses = {
    200: unknown;
};

export type AgentControllerUpdateData = {
    body: UpdateAgentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentControllerUpdateResponses = {
    200: unknown;
};

export type AgentControllerRestartData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}/restart';
};

export type AgentControllerRestartResponses = {
    201: unknown;
};

export type FileControllerListData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/files';
};

export type FileControllerListResponses = {
    200: unknown;
};

export type FileControllerReadData = {
    body?: never;
    path: {
        agentId: string;
    };
    query: {
        path: string;
    };
    url: '/agents/{agentId}/files/content';
};

export type FileControllerReadResponses = {
    200: unknown;
};

export type FileControllerSaveData = {
    body: SaveFileDto;
    path: {
        agentId: string;
    };
    query: {
        path: string;
    };
    url: '/agents/{agentId}/files/content';
};

export type FileControllerSaveResponses = {
    200: unknown;
};

export type LogControllerGetLogsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query: {
        tail: string;
    };
    url: '/agents/{agentId}/logs';
};

export type LogControllerGetLogsResponses = {
    200: unknown;
};

export type UserControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UserControllerFindAllResponses = {
    200: unknown;
};

export type UserControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type UserControllerCreateResponses = {
    201: unknown;
};

export type UserControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerRemoveResponses = {
    200: unknown;
};

export type UserControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerFindByIdResponses = {
    200: unknown;
};

export type UserControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerUpdateResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    200: unknown;
};

export type SendBridleMessageData = {
    body: SendMessageDto;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/agent/{botId}/message';
};

export type SendBridleMessageResponses = {
    200: unknown;
};

export type SendBridleMessageSyncData = {
    body: SendMessageDto;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/agent/{botId}/message/sync';
};

export type SendBridleMessageSyncResponses = {
    200: unknown;
};

export type BridleHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/health';
};

export type BridleHealthResponses = {
    200: BridleHealthDto;
};

export type BridleHealthResponse = BridleHealthResponses[keyof BridleHealthResponses];

export type BridleBotHealthData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/agent/{botId}/health';
};

export type BridleBotHealthResponses = {
    200: BridleBotHealthDto;
};

export type BridleBotHealthResponse = BridleBotHealthResponses[keyof BridleBotHealthResponses];

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/list';
};

export type ListAgentsResponses = {
    200: unknown;
};

export type UsageControllerFindForAgentData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/usage';
};

export type UsageControllerFindForAgentResponses = {
    200: unknown;
};

export type UsageControllerReportData = {
    body: ReportUsageDto;
    headers: {
        'x-bridle-api-key': string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/usage';
};

export type UsageControllerReportResponses = {
    204: void;
};

export type UsageControllerReportResponse = UsageControllerReportResponses[keyof UsageControllerReportResponses];

export type GetKnowledgesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/knowledges';
};

export type GetKnowledgesResponses = {
    200: unknown;
};

export type CreateKnowledgeData = {
    body: CreateKnowledgeDto;
    path?: never;
    query?: never;
    url: '/knowledges';
};

export type CreateKnowledgeResponses = {
    201: unknown;
};

export type GetKnowledgeStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/knowledges/status';
};

export type GetKnowledgeStatusResponses = {
    200: unknown;
};

export type GetGraphLabelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/knowledges/graph/labels';
};

export type GetGraphLabelsResponses = {
    200: unknown;
};

export type GetGraphData = {
    body?: never;
    path?: never;
    query: {
        label: string;
        maxDepth?: number;
        maxNodes?: number;
    };
    url: '/knowledges/graph';
};

export type GetGraphResponses = {
    200: GraphDto;
};

export type GetGraphResponse = GetGraphResponses[keyof GetGraphResponses];

export type DeleteKnowledgeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}';
};

export type DeleteKnowledgeResponses = {
    204: void;
};

export type DeleteKnowledgeResponse = DeleteKnowledgeResponses[keyof DeleteKnowledgeResponses];

export type GetKnowledgeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}';
};

export type GetKnowledgeResponses = {
    200: unknown;
};

export type UpdateKnowledgeData = {
    body: UpdateKnowledgeDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}';
};

export type UpdateKnowledgeResponses = {
    200: unknown;
};

export type IndexKnowledgeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}/index';
};

export type IndexKnowledgeResponses = {
    202: unknown;
};

export type QueryKnowledgeData = {
    body: QueryKnowledgeDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}/query';
};

export type QueryKnowledgeResponses = {
    200: KnowledgeQueryResultDto;
};

export type QueryKnowledgeResponse = QueryKnowledgeResponses[keyof QueryKnowledgeResponses];

export type GetKnowledgeSourcesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}/sources';
};

export type GetKnowledgeSourcesResponses = {
    200: unknown;
};

export type AddKnowledgeSourceData = {
    body: CreateSourceDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledges/{id}/sources';
};

export type AddKnowledgeSourceResponses = {
    201: unknown;
};

export type DeleteKnowledgeSourceData = {
    body?: never;
    path: {
        id: string;
        sourceId: string;
    };
    query?: never;
    url: '/knowledges/{id}/sources/{sourceId}';
};

export type DeleteKnowledgeSourceResponses = {
    204: void;
};

export type DeleteKnowledgeSourceResponse = DeleteKnowledgeSourceResponses[keyof DeleteKnowledgeSourceResponses];

export type SkillControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/skills';
};

export type SkillControllerFindAllResponses = {
    200: unknown;
};

export type SkillControllerCreateData = {
    body: CreateSkillDto;
    path?: never;
    query?: never;
    url: '/skills';
};

export type SkillControllerCreateResponses = {
    201: unknown;
};

export type SkillControllerListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/skills/sources';
};

export type SkillControllerListSourcesResponses = {
    200: unknown;
};

export type SkillControllerSearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/skills/search';
};

export type SkillControllerSearchResponses = {
    200: unknown;
};

export type SkillControllerImportFromUrlData = {
    body: ImportSkillUrlDto;
    path?: never;
    query?: never;
    url: '/skills/import-url';
};

export type SkillControllerImportFromUrlResponses = {
    201: unknown;
};

export type SkillControllerImportFromGithubData = {
    body: ImportSkillDto;
    path?: never;
    query?: never;
    url: '/skills/import';
};

export type SkillControllerImportFromGithubResponses = {
    201: unknown;
};

export type SkillControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/skills/{id}';
};

export type SkillControllerRemoveResponses = {
    200: unknown;
};

export type SkillControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/skills/{id}';
};

export type SkillControllerFindByIdResponses = {
    200: unknown;
};

export type SkillControllerUpdateData = {
    body: UpdateSkillDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/skills/{id}';
};

export type SkillControllerUpdateResponses = {
    200: unknown;
};

export type ClientOptions = {
    baseURL: string;
};