// This file is auto-generated by @hey-api/openapi-ts

export type CreateOwnerDto = {
    name: string;
    email: string;
    password: string;
};

export type UpsertSettingDto = {
    valueType: 'string' | 'json';
    /**
     * String for valueType=string; any JSON for valueType=json
     */
    value: {
        [key: string]: unknown;
    };
};

export type CreateTemplateDto = {
    name: string;
    description: string;
    image: string;
    defaultConfig?: {
        [key: string]: unknown;
    };
    defaultResources?: {
        [key: string]: unknown;
    };
};

export type UpdateTemplateDto = {
    name?: string;
    description?: string;
    image?: string;
    defaultConfig?: {
        [key: string]: unknown;
    };
    defaultResources?: {
        [key: string]: unknown;
    };
};

export type AgentResourcesDto = {
    cpu: string;
    memory: string;
};

export type CreateAgentDto = {
    name: string;
    templateId: string;
    config?: {
        [key: string]: unknown;
    };
    resources?: AgentResourcesDto;
};

export type UpdateAgentDto = {
    name?: string;
    templateId?: string;
    config?: {
        [key: string]: unknown;
    };
    resources?: AgentResourcesDto;
};

export type CreateUserDto = {
    name: string;
    email: string;
    password: string;
    role?: 'owner' | 'admin' | 'member';
};

export type UpdateUserDto = {
    name?: string;
    email?: string;
    password?: string;
    role?: 'owner' | 'admin' | 'member';
    status?: 'active' | 'invited' | 'disabled';
};

export type LoginDto = {
    email: string;
    password: string;
};

export type BridleTextPartDto = {
    type: 'text' | 'image' | 'file';
    text: string;
};

export type BridleImagePartDto = {
    type: 'text' | 'image' | 'file';
    /**
     * Base64-encoded image data
     */
    base64: string;
    /**
     * MIME type
     */
    mediaType: string;
};

export type SendMessageDto = {
    /**
     * Message text (plain-text shorthand)
     */
    text: string;
    /**
     * Rich content parts. If omitted, built from text + images.
     */
    parts?: Array<BridleTextPartDto>;
    /**
     * Attached images (legacy — prefer parts)
     */
    images?: Array<BridleImagePartDto>;
};

export type BridleHealthDto = {
    ok: boolean;
    /**
     * Whether any agent runtime is connected via WebSocket
     */
    agentConnected: boolean;
    /**
     * Number of browser clients connected
     */
    browserClients: number;
};

export type BridleBotHealthDto = {
    ok: boolean;
    /**
     * Whether this bot agent is connected via WebSocket
     */
    agentConnected: boolean;
    /**
     * Number of browser clients connected to this bot
     */
    browserClients: number;
    /**
     * Bot identifier
     */
    botId: string;
};

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthControllerCheckResponses = {
    200: unknown;
};

export type InitControllerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/setup/status';
};

export type InitControllerStatusResponses = {
    200: unknown;
};

export type InitControllerInitData = {
    body: CreateOwnerDto;
    path?: never;
    query?: never;
    url: '/setup/init';
};

export type InitControllerInitResponses = {
    201: unknown;
};

export type SettingControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type SettingControllerFindAllResponses = {
    200: unknown;
};

export type SettingControllerFindByGroupData = {
    body?: never;
    path: {
        group: string;
    };
    query?: never;
    url: '/settings/{group}';
};

export type SettingControllerFindByGroupResponses = {
    200: unknown;
};

export type SettingControllerRemoveData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/settings/{group}/{name}';
};

export type SettingControllerRemoveResponses = {
    200: unknown;
};

export type SettingControllerFindByKeyData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/settings/{group}/{name}';
};

export type SettingControllerFindByKeyResponses = {
    200: unknown;
};

export type SettingControllerUpsertData = {
    body: UpsertSettingDto;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/settings/{group}/{name}';
};

export type SettingControllerUpsertResponses = {
    200: unknown;
};

export type TemplateControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates';
};

export type TemplateControllerFindAllResponses = {
    200: unknown;
};

export type TemplateControllerCreateData = {
    body: CreateTemplateDto;
    path?: never;
    query?: never;
    url: '/templates';
};

export type TemplateControllerCreateResponses = {
    201: unknown;
};

export type TemplateControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/templates/{id}';
};

export type TemplateControllerRemoveResponses = {
    200: unknown;
};

export type TemplateControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/templates/{id}';
};

export type TemplateControllerFindByIdResponses = {
    200: unknown;
};

export type TemplateControllerUpdateData = {
    body: UpdateTemplateDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/templates/{id}';
};

export type TemplateControllerUpdateResponses = {
    200: unknown;
};

export type AgentControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentControllerFindAllResponses = {
    200: unknown;
};

export type AgentControllerCreateData = {
    body: CreateAgentDto;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentControllerCreateResponses = {
    201: unknown;
};

export type AgentControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentControllerRemoveResponses = {
    200: unknown;
};

export type AgentControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentControllerFindByIdResponses = {
    200: unknown;
};

export type AgentControllerUpdateData = {
    body: UpdateAgentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type AgentControllerUpdateResponses = {
    200: unknown;
};

export type AgentControllerRestartData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agents/{id}/restart';
};

export type AgentControllerRestartResponses = {
    201: unknown;
};

export type LogControllerGetLogsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/logs';
};

export type LogControllerGetLogsResponses = {
    200: unknown;
};

export type UserControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UserControllerFindAllResponses = {
    200: unknown;
};

export type UserControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type UserControllerCreateResponses = {
    201: unknown;
};

export type UserControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerRemoveResponses = {
    200: unknown;
};

export type UserControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerFindByIdResponses = {
    200: unknown;
};

export type UserControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerUpdateResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    200: unknown;
};

export type SendBridleMessageData = {
    body: SendMessageDto;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/agent/{botId}/message';
};

export type SendBridleMessageResponses = {
    200: unknown;
};

export type SendBridleMessageSyncData = {
    body: SendMessageDto;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/agent/{botId}/message/sync';
};

export type SendBridleMessageSyncResponses = {
    200: unknown;
};

export type BridleHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/health';
};

export type BridleHealthResponses = {
    200: BridleHealthDto;
};

export type BridleHealthResponse = BridleHealthResponses[keyof BridleHealthResponses];

export type BridleBotHealthData = {
    body?: never;
    path: {
        botId: string;
    };
    query?: never;
    url: '/api/agent/{botId}/health';
};

export type BridleBotHealthResponses = {
    200: BridleBotHealthDto;
};

export type BridleBotHealthResponse = BridleBotHealthResponses[keyof BridleBotHealthResponses];

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/list';
};

export type ListAgentsResponses = {
    200: unknown;
};

export type ClientOptions = {
    baseURL: string;
};